# visit http://jekyllrb.com/docs/configuration/ for more settings

paginate: 10
paginate_path: "page:num"
exclude: [".gitignore", "README.md", "BACKLOG.md", "SETUP.md", "CHANGELOG.md", "Rakefile.rb", "Gemfile", "Gemfile.lock"]
pygments: true
markdown: redcarpet
permalink: /blog/:year/:month/:day/:title
timezone: Europe/Berlin
encoding: UTF-8
destination: ./_site/
#baseurl:     /blog
url:         http://localhost:4000
#BASE_PATH: /blog

title: Infrastruktur mit Qualität
description: Infrastruktur mit Qualität gestalten und betreiben
name: www.infrabricks.de

keywords:
    - serverspec
    - infrastructur as code
    - test
    - serverspec tutorial

author:
  name: Peter Rossbach
  email: peter.rossbach@bee42.com
  short: pr
  image: rossbach_peter.jpg
  github: rossbachp
  linkedin: ../pub/peter-rossbach/0/a48/838
  xing: Peter_Rossbach
  bio: Systemarchitekt, Infra-Coder, Trainer, Apache Tomcat Committer, Softwareentwickler

authors:
  - rossbachp:
    id: 1
    name: Peter Roßbach
    short: pr
    email: peter.rossbach@bee42.com
    image: rossbach_peter.jpg
    sidebarimage: peter_rossbach_small.png
    github: rossbachp
    linkedin: ../pub/peter-rossbach/0/a48/838
    twitter: PRossbach
    xing: Peter_Rossbach
    bio: Systemarchitekt, Infra-Coder, Trainer, Softwareentwickler, Apache Tomcat Committer
  - schmidta:
    id: 2
    name: Andreas Schmidt
    short: as
    email: andreas.schmidt@dp-mail.de
    github: aschmidt75
    twitter: aschmidt75
    image: schmidt_andreas.jpg
    linkedin: ../pub/andreas-schmidt/4/b67/24a
    xing: Andreas_Schmidt38
    sidebarimage: andreas_schmidt_small.png
    bio: Infra-Coder, System Engineer, Softwareentwickler

rss_path: rss.xml
atom_path: atom.xml
categories_path: categories.html
tags_path: tags.html
links_path: links.html

analytics:
   google:
     tracking_id: 'UA-48463790-3'
     name: 'infrabricks.de'
